# Generated by Django 2.2.1 on 2019-06-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_model', models.CharField(max_length=256)),
                ('sensor_mp', models.IntegerField()),
                ('brand', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ('brand', 'camera_model'),
            },
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('brand', models.CharField(max_length=256)),
                ('serial_number', models.CharField(max_length=256)),
                ('cameras', models.ManyToManyField(to='Oauth2_test.Camera')),
            ],
            options={
                'ordering': ('brand', 'name', 'serial_number'),
            },
        ),
        migrations.AddConstraint(
            model_name='camera',
            constraint=models.UniqueConstraint(fields=('camera_model', 'brand'), name='unique_camera'),
        ),
        migrations.AddConstraint(
            model_name='drone',
            constraint=models.UniqueConstraint(fields=('name', 'brand', 'serial_number'), name='unique_drone'),
        ),
    ]
